public/index.html
Fixed #3 
- Added header with form.
- Added welcome/info text in the body.
=> Added header form and welcome massage

public/index.html
Fixed #14
- Linked materialize css and js from CDN
- Linked google icons from CDN
=> Linked materialize and google fonts

public/index.html, public/js/main.js
Fixed #5 
- Adds various helpers for queryselecting
- Adds a function to clear wrapper
- Adds a function to append all elements in a list to wrapper
- Adds a function that generates a list of elements from a filtered/processed list of repositories
- Adds a template to index.html
- linting is supposed to fail for QSA, resetWrapper, appendToWrapper, generateRepoCard and tempfunction. The former 4 are due to them being necessary/helpful later, and the last one due to being supposed to call an as-of-yet unnamed function.
- impossible :hubris:
=> Generate cards for repository list

.gitignore, public/css/main.css, public/index.html
Fixed #24 
Added style
Added style on header/wrapper, and updated text in wrapper
=> Added wrapper/header style

server.rb
The get route has been fixed.
Fixed #30
- Fixed get route (Added a / infront of api/github)
=> Fix of invalid GET route

public/js/main.js
Fixed #34 
- Adds function to parse data from GitHub API into a list of objects for use in generating "repo cards"
- Linting still doesn't approve. It's still intentional
- You tell me
=> Parse repo data returned from GH API

public/index.html, public/js/main.js, server.rb
Fixed #37 
Added so when a GitHub username is given, wrapper generates cards.
Also added, invalid request. Such as non existing username or that
the server is not responding. 
=> Added feauture, when input is given. Cards is generated

public/css/main.css, public/index.html
Fixed #42 
Added style to the template cards, so they are now readable :shipit: 
:shipit:
=> Added very nice style to the template cards

public/js/main.js
Fixed #48
- Removed hardcoding
=> Resolved hardcoding

public/index.html, public/js/main.js
Fixed #55
- Allow for dynamic syntax highlighting
=> Added dynamic syntax highlighting

public/js/main.js
Fixed #67 
- Handles issue where manifest.filePath doesn't lead to a file
=> manifest.filePath not leading to a file is now handled

public/css/main.css
Fixed #60 
Added hover function to the cursor
=> Added improvment to the cursor

public/css/main.css, public/index.html
Fixed #53
- Fixed radio buttons on fork cards
=> Make radiobuttons work again

public/css/main.css, public/index.html
Fixed #56 
Added style of the repo cards
=> Added style to the repocards

public/js/main.js
Fixed #47
- Renamed function "generateForkCards"
- Implemented helpers
- Add comments and update documentation
=> Implemented helpers and renamed "generateForkCards"

server.rb
Fixed #79 
- Added comments for the server.rb file.
=> Added comments to thesserver.rb file

public/js/main.js
Fixed #46
- Added comments to functions and complicated parts in main.js
=> Added comments to JS

docs/index.html
- Updated document title for documentation.
- Made foo better.
=> Updated documentation title

public/css/main.css, public/js/main.js
Fixed #29
- Gives a accent color to the card if it does not contain a manifest file 
=> Gives a accent color to the card if it does not contain a manifest file

public/css/main.css, public/js/main.js
Fixed #7
- Dynamically run tests for js based on `.manifest.json` content
=> Dynamically test JS code

db/seed.rb
Fixed #92 
Added seed file with necessary data
=> Added seed file to our database
